openapi: 3.0.0
info:
  title: Cryptocurrency API
  version: 1.0.0
  description: API for managing cryptocurrencies
servers:
  - url: http://localhost:3000
paths:
  /cryptocurrency/{id}:
    get:
      summary: Search a cryptocurrency by Id
      parameters:
        - in: path
          name: id
          description: ID of the cryptocurrency
          schema:
            type: integer
            format: int64
          required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cryptocurrency'
        '404':
          description: Cryptocurrency not found
  /transaction:
    post:
      summary: Create Transaction
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateTransactionDto'
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Transaction'
  /transaction/receiver/{receiverId}:
    get:
      summary: Search transactions by receiver id
      parameters:
        - in: path
          name: receiverId
          description: ID of the receiver
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/GetTransactionDto'
        '404':
          description: Transactions not found for the receiver
  /transaction/sender/{senderId}:
    get:
      summary: Search transactions by sender id
      parameters:
        - in: path
          name: senderId
          description: ID of the sender
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/GetTransactionDto'
        '404':
          description: Transactions not found for the sender
components:
  schemas:
    Cryptocurrency:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        symbol:
          type: string
    CreateTransactionDto:
      type: object
      properties:
        cryptocurrency_id:
          type: integer
          format: int64
        sender:
          type: string
          maxLength: 100
        receiver:
          type: string
          maxLength: 100
        amount:
          type: number
          format: double
    Transaction:
      type: object
      properties:
        id:
          type: integer
          format: int64
        cryptocurrency_id:
          type: integer
          format: int64
        sender:
          type: string
          maxLength: 100
        receiver:
          type: string
          maxLength: 100
        amount:
          type: number
          format: double
        createdDate:
          type: string
          format: date-time
    GetTransactionDto:
      type: object
      properties:
        id:
          type: integer
          format: int64
        cryptocurrency_id:
          type: integer
          format: int64
        sender:
          type: string
